# CCline 配置文件示例
# 复制此文件为 config.toml 并修改相应配置

# 主题设置
theme = "dark"

# 是否首次运行
first_run = false

# JWT Token 配置 (用于排名功能)
# 从 PackyCode 网站获取您的 JWT token 并填入下方
jwt_token = "your_jwt_token_here"

# 状态栏段落配置
[segments]
# 目录显示
directory = true

# Git 信息
git = true

# 模型信息
model = true

# 使用情况
usage = true

# 配额信息 (包含排名功能)
quota = true

# 时间显示
time = false

# 末尾表情
emoji = false

# 旋转动画
spinner = true

# 网络延迟
network = false

# 排名功能
ranking = true
